package cz.masci.wizard.simple;

import cz.masci.wizard.api.step.HierarchicalStep;
import cz.masci.wizard.api.step.LeafStep;
import cz.masci.wizard.api.step.StepState;
import lombok.Data;

/**
 * A simple mutable implementation of {@link StepState}.
 *
 * <p>Holds references to the currently active {@link LeafStep} and {@link HierarchicalStep}
 * as the wizard navigates through its step tree.
 * All getters and setters are generated by Lombok's {@code @Data}.</p>
 *
 * @param <H> the type of the status value held by the {@link HierarchicalStep}
 * @param <L> the type of the value held by the {@link LeafStep}
 */
@Data
public class SimpleStepState<H, L> implements StepState<H, L> {
  /** The currently active leaf step, or {@code null} when positioned on a hierarchical step. */
  private LeafStep<L> leafStep;
  /** The currently active hierarchical step, or {@code null} when at the root level. */
  private HierarchicalStep<H> hierarchicalStep;

  /**
   * Creates a new {@code SimpleStepState} with no active leaf or hierarchical step.
   * Use the setters to configure the state as the wizard navigates.
   */
  public SimpleStepState() {
  }
}
