name: Publish Release

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  publish:
    name: Publish package to Maven Central Repository
    # Only run if the PR was merged (not just closed)
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ steps.generate-token.outputs.token }}

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
          server-id: central  # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: MAVEN_USERNAME # env variable for username in deploy
          server-password: MAVEN_CENTRAL_TOKEN # env variable for token in deploy
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }} # Value of the GPG private key to import - without any modification
          gpg-passphrase: MAVEN_GPG_PASSPHRASE  # env variable for GPG private key passphrase

      - name: Publish package
        id: publish-to-central
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SECRET_KEY_PASSWORD }}
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          mvn \
            --no-transfer-progress \
            --batch-mode \
            release:prepare release:perform
