name: Verify on Pull Request

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]

jobs:
  verify:
    name: Verify Maven package with release profile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Java for maven
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }} # Value of the GPG private key to import - without any modification
          gpg-passphrase: MAVEN_GPG_PASSPHRASE  # env variable for GPG private key passphrase

      - name: Verify package
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SECRET_KEY_PASSWORD }}
        run: |
          mvn verify -Prelease --no-transfer-progress 
